from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
ARTIFACTS_DIR = BASE_DIR / "artifacts"
CHECKPOINT_DIR = ARTIFACTS_DIR / "checkpoints"
HEATMAP_DIR = ARTIFACTS_DIR / "heatmaps"
CALIBRATION_DIR = ARTIFACTS_DIR / "calibration"
CALIBRATION_FILE = CALIBRATION_DIR / "thresholds.json"

MODEL_VERSION = "hybrid-v1"
CLASS_NAMES = ["Benign", "Malignant"]
IMAGE_SIZE = 224

CT_TARGET_SPACING_MM = (1.0, 1.0, 1.0)
CT_LUNG_WINDOW_CENTER = -600.0
CT_LUNG_WINDOW_WIDTH = 1500.0

TEMPERATURE_SCALING = 1.15
MALIGNANCY_THRESHOLD_SCREENING = 0.35
MALIGNANCY_THRESHOLD_DIAGNOSTIC = 0.50

QUALITY_GATE_MIN_SCORE = 0.45
QUALITY_GATE_MIN_CT_STD = 18.0
QUALITY_GATE_MIN_XRAY_CONTRAST = 20.0

FOCAL_LOSS_GAMMA = 2.0
FOCAL_LOSS_ALPHA = 0.35
HARD_NEGATIVE_MIN_CONFIDENCE = 0.60
CALIBRATION_GRID_MIN = 0.20
CALIBRATION_GRID_MAX = 0.80
CALIBRATION_GRID_STEP = 0.02

for directory in (ARTIFACTS_DIR, CHECKPOINT_DIR, HEATMAP_DIR, CALIBRATION_DIR):
    directory.mkdir(parents=True, exist_ok=True)
